// TEMPORARY DATA

export let role = "admin";

export const teachersData = [
    {
        id: 1,
        teacherId: "1235067890",
        name: "دکتر علی احمدی",
        email: "ali@ahmadi.com",
        photo: "https://wallpapercave.com/wp/wp8888840.jpg",
        phone: "1235067890",
        subjects: ["ریاضیات", "هندسه"],
        classes: ["۱B", "۲A", "۳C"],
        address: "خیابان ولیعصر ۱۲۳، تهران",
    },
    {
        id: 2,
        teacherId: "1235067890",
        name: "فاطمه امیری",
        email: "fatemeh@amiri.com",
        photo: "https://wallpapercave.com/uwp/uwp4578596.jpeg",
        phone: "1235067890",
        subjects: ["فیزیک", "شیمی"],
        classes: ["۵A", "۴B", "۳C"],
        address: "خیابان انقلاب ۱۲۳، تهران",
    },
    {
        id: 3,
        teacherId: "1235067890",
        name: "محمد گلی",
        email: "mohammad@goli.com",
        photo: "https://wallpapercave.com/wp/wp14790528.webp",
        phone: "1235067890",
        subjects: ["زیست شناسی"],
        classes: ["۵A", "۴B", "۳C"],
        address: "خیابان فردوسی ۱۲۳، تهران",
    },
    {
        id: 4,
        teacherId: "1235067890",
        name: "آرش فرامرزی",
        email: "arash@gmail.com",
        photo: "https://wallpapercave.com/wp/wp9946934.jpg",
        phone: "1235067890",
        subjects: ["تاریخ"],
        classes: ["۵A", "۴B", "۳C"],
        address: "خیابان بهار ۱۲۳، تهران",
    },
    {
        id: 5,
        teacherId: "1235067890",
        name: "مریم سمیعی",
        email: "maryam@gmail.com",
        photo: "https://wallpapercave.com/wp/wp3635883.jpg",
        phone: "1235067890",
        subjects: ["موسیقی", "تاریخ"],
        classes: ["۵A", "۴B", "۳C"],
        address: "خیابان حافظ ۱۲۳، تهران",
    },
    {
        id: 6,
        teacherId: "1235067890",
        name: "لیلا حسینی",
        email: "leila@gmail.com",
        photo: "https://wallpapercave.com/wp/wp3635857.jpg",
        phone: "1235067890",
        subjects: ["فیزیک"],
        classes: ["۵A", "۴B", "۳C"],
        address: "خیابان شیراز ۱۲۳، تهران",
    },
    {
        id: 7,
        teacherId: "1235067890",
        name: "رضا جلیلی",
        email: "reza@jafari.com",
        photo: "https://wallpapercave.com/uwp/uwp4578088.jpeg",
        phone: "1235067890",
        subjects: ["زبان", "اسپانیایی"],
        classes: ["۵A", "۴B", "۳C"],
        address: "خیابان آزادی ۱۲۳، تهران",
    },
    {
        id: 8,
        teacherId: "1234567890",
        name: "سارا اسلامی",
        email: "sara@castro.com",
        photo: "https://wallpapercave.com/uwp/uwp4579153.png",
        phone: "1234567890",
        subjects: ["ریاضیات", "هندسه"],
        classes: ["۵A", "۴B", "۳C"],
        address: "خیابان انقلاب ۱۲۳، اصفهان",
    },
    {
        id: 9,
        teacherId: "1234567890",
        name: "علی اسدی",
        email: "ali@briggs.com",
        photo: "https://wallpapercave.com/wp/wp2023517.jpg",
        phone: "1234567890",
        subjects: ["ادبیات", "زبان"],
        classes: ["۵A", "۴B", "۳C"],
        address: "خیابان امام خمینی ۱۲۳، تهران",
    },
    {
        id: 10,
        teacherId: "1234567890",
        name: "سینا غلامی",
        email: "sina@gholami.com",
        photo: "https://wallpapercave.com/wp/wp10864291.jpg",
        phone: "1234567890",
        subjects: ["زیست شناسی"],
        classes: ["۵A", "۴B", "۳C"],
        address: "خیابان آزادی ۱۲۳، تهران",
    },
];

export const studentsData = [
    {
        id: 1,
        studentId: "1234567890",
        name: "امیرحسین احمدی",
        email: "amirhossein@ahmadi.com",
        photo: "https://wallpapercave.com/wp/wp8888840.jpg",
        phone: "1234567890",
        grade: "کارشناسی",
        class: "۱B",
        address: "خیابان ولیعصر ۱۲۳، تهران",
    },
    {
        id: 2,
        studentId: "1234567890",
        name: "سمیرا احمدی",
        email: "samira@ahmadi.com",
        photo: "https://wallpapercave.com/wp/wp8888840.jpg",
        phone: "1234567890",
        grade: "کارشناسی",
        class: "۵A",
        address: "خیابان انقلاب ۱۲۳، تهران",
    },
    {
        id: 3,
        studentId: "1234567890",
        name: "محمد گلی",
        email: "mohammad@goli.com",
        photo: "https://wallpapercave.com/wp/wp8888840.jpg",
        phone: "1234567890",
        grade: "کارشناسی",
        class: "۵A",
        address: "خیابان فردوسی ۱۲۳، تهران",
    },
    {
        id: 4,
        studentId: "1234567890",
        name: "آرش فرامرزی",
        email: "arash@gmail.com",
        photo: "https://wallpapercave.com/wp/wp8888840.jpg",
        phone: "1234567890",
        grade: "Ph.D",
        class: "۵A",
        address: "خیابان بهار ۱۲۳، تهران",
    },
    {
        id: 5,
        studentId: "1234567890",
        name: "نازنین سمیعی",
        email: "nazanin@gmail.com",
        photo: "https://wallpapercave.com/wp/wp8888840.jpg",
        phone: "1234567890",
        grade: "کارشناسی",
        class: "۵A",
        address: "خیابان حافظ ۱۲۳، تهران",
    },
    {
        id: 6,
        studentId: "1234567890",
        name: "لیلا حسینی",
        email: "leila@gmail.com",
        photo: "https://wallpapercave.com/wp/wp8888840.jpg",
        phone: "1234567890",
        grade: "کارشناسی",
        class: "۵A",
        address: "خیابان شیراز ۱۲۳، تهران",
    },
    {
        id: 7,
        studentId: "1234567890",
        name: "مریم جلیلی",
        email: "maryam@jafari.com",
        photo: "https://wallpapercave.com/wp/wp8888840.jpg",
        phone: "1234567890",
        grade: "کارشناسی",
        class: "۵A",
        address: "خیابان انقلاب ۱۲۳، اصفهان",
    },
    {
        id: 8,
        studentId: "1234567890",
        name: "علیرضا اسلامی",
        email: "alireza@castro.com",
        photo: "https://wallpapercave.com/wp/wp8888840.jpg",
        phone: "1234567890",
        grade: "کارشناسی",
        class: "۵A",
        address: "خیابان آزادی ۱۲۳، تهران",
    },
    {
        id: 9,
        studentId: "1234567890",
        name: "سپیده برجسته",
        email: "sepideh@briggs.com",
        photo: "https://wallpapercave.com/wp/wp8888840.jpg",
        phone: "1234567890",
        grade: "کارشناسی",
        class: "۵A",
        address: "خیابان انقلاب ۱۲۳، تهران",
    },
    {
        id: 10,
        studentId: "1234567890",
        name: "رضا غلامی",
        email: "reza@gholami.com",
        photo: "https://wallpapercave.com/wp/wp8888840.jpg",
        phone: "1234567890",
        grade: "کارشناسی",
        class: "۵A",
        address: "خیابان امام خمینی ۱۲۳، تهران",
    },
];

export const parentsData = [
    {
        id: 1,
        name: "علی احمدی",
        students: ["سارا احمدی"],
        email: "ali@ahmadi.com",
        phone: "09123456789",
        address: "خیابان اصلی ۱۲۳، تهران",
    },
    {
        id: 2,
        name: "فاطمه محمدی",
        students: ["سیما محمدی"],
        email: "fatemeh@mohammadi.com",
        phone: "09123456789",
        address: "خیابان انقلاب ۱۲۳، تهران",
    },
    {
        id: 3,
        name: "محمود جلالی",
        students: ["فاطمه جلالی"],
        email: "mahmood@jalali.com",
        phone: "09123456789",
        address: "خیابان شریعتی ۱۲۳، تهران",
    },
    {
        id: 4,
        name: "مسعود صفری",
        students: ["مریم صفری", "امیر صفری"],
        email: "masoud@sefri.com",
        phone: "09123456789",
        address: "خیابان آزادی ۱۲۳، تهران",
    },
    {
        id: 5,
        name: "مینا نیکو",
        students: ["آرزو نیکو"],
        email: "mina@nikoo.com",
        phone: "09123456789",
        address: "خیابان ولیعصر ۱۲۳، تهران",
    },
    {
        id: 6,
        name: "محمد حسین",
        students: ["امیر حسین"],
        email: "mohammad@hossein.com",
        phone: "09123456789",
        address: "خیابان قزوین ۱۲۳، تهران",
    },
    {
        id: 7,
        name: "مهدی جعفری",
        students: ["فرشاد جعفری", "لیلا جعفری"],
        email: "mehdi@jafari.com",
        phone: "09123456789",
        address: "خیابان سعدی ۱۲۳، تهران",
    },
    {
        id: 8,
        name: "سارا فلاحی",
        students: ["مهدی فلاحی"],
        email: "sara@fallahi.com",
        phone: "09123456789",
        address: "خیابان پاستور ۱۲۳، تهران",
    },
    {
        id: 9,
        name: "آرمان رحیمی",
        students: ["علی رحیمی", "ندا رحیمی"],
        email: "arman@rahimi.com",
        phone: "09123456789",
        address: "خیابان جردن ۱۲۳، تهران",
    },
    {
        id: 10,
        name: "سعید موسوی",
        students: ["ندا موسوی"],
        email: "saeed@mosavi.com",
        phone: "09123456789",
        address: "خیابان نیاوران ۱۲۳، تهران",
    },
];

export const subjectsData = [
    {
        id: 1,
        name: "ریاضیات",
        teachers: ["محمد رضا حسینی", "احمد کاویانی"],
    },
    {
        id: 2,
        name: "زبان",
        teachers: ["سارا موسوی", "امیر شجاعی"],
    },
    {
        id: 3,
        name: "فیزیک",
        teachers: ["پرویز احمدی", "مریم عطایی"],
    },
    {
        id: 4,
        name: "شیمی",
        teachers: ["مهسا پورمحمدی", "ناصر کریمی"],
    },
    {
        id: 5,
        name: "زیست‌",
        teachers: ["زهرا اسکندری", "سعید قاسمی"],
    },
    {
        id: 6,
        name: "تاریخ",
        teachers: ["محمد علی دهقان", "علی کاظمی"],
    },
    {
        id: 7,
        name: "جغرافیا",
        teachers: ["حسین جبارزاده", "مریم نیکو"],
    },
    {
        id: 8,
        name: "هنر",
        teachers: ["ندا رمضانی", "فرشته فاضلی"],
    },
    {
        id: 9,
        name: "موسیقی",
        teachers: ["کیانوش کریمی", "سهیلا ملکی"],
    },
    {
        id: 10,
        name: "ادبیات فارسی",
        teachers: ["حسن احمدی", "حمید رضا غلامی"],
    },
];

export const classesData = [
    {
        id: 1,
        name: "۱A",
        capacity: 20,
        grade: "کاردانی",
        supervisor: "حسین قربانی",
    },
    {
        id: 2,
        name: "۲B",
        capacity: 22,
        grade: "کاردانی",
        supervisor: "علیرضا سلیمی",
    },
    {
        id: 3,
        name: "۳C",
        capacity: 20,
        grade: "کاردانی",
        supervisor: "محمود فتحی",
    },
    {
        id: 4,
        name: "۴B",
        capacity: 18,
        grade: "کاردانی",
        supervisor: "مهدی مرادی",
    },
    {
        id: 5,
        name: "۵A",
        capacity: 16,
        grade: "کارشناسی",
        supervisor: "زهره محمدی",
    },
    {
        id: 6,
        name: "۵B",
        capacity: 20,
        grade: "کارشناسی",
        supervisor: "علی بهرامی",
    },
    {
        id: 7,
        name: "۷A",
        capacity: 18,
        grade: "ارشد",
        supervisor: "فاطمه احمدی",
    },
    {
        id: 8,
        name: "۶B",
        capacity: 22,
        grade: "ارشد",
        supervisor: "علی نیکو",
    },
    {
        id: 9,
        name: "۶C",
        capacity: 18,
        grade: "ارشد",
        supervisor: "مینا کیانی",
    },
    {
        id: 10,
        name: "۶D",
        capacity: 20,
        grade: "ارشد",
        supervisor: "نیکو رضایی",
    },
];

export const lessonsData = [
    {
        id: 1,
        subject: "ریاضیات",
        class: "۱A",
        teacher: "سینا رضایی",
    },
    {
        id: 2,
        subject: "زبان",
        class: "۲A",
        teacher: "زهرا سلیمانی",
    },
    {
        id: 3,
        subject: "علوم",
        class: "۳A",
        teacher: "فاطمه احمدی",
    },
    {
        id: 4,
        subject: "مطالعات اجتماعی",
        class: "۱B",
        teacher: "کامران جلالی",
    },
    {
        id: 5,
        subject: "هنر",
        class: "۴A",
        teacher: "علی محمدی",
    },
    {
        id: 6,
        subject: "موسیقی",
        class: "۵A",
        teacher: "سمیه ابراهیمی",
    },
    {
        id: 7,
        subject: "تاریخ",
        class: "۶A",
        teacher: "سعید محمدی",
    },
    {
        id: 8,
        subject: "جغرافیا",
        class: "۶B",
        teacher: "مریم یوسفی",
    },
    {
        id: 9,
        subject: "فیزیک",
        class: "۶C",
        teacher: "احمد صالحی",
    },
    {
        id: 10,
        subject: "شیمی",
        class: "۴B",
        teacher: "مهدی فتحی",
    },
];

export const examsData = [
    {
        id: 1,
        subject: "ریاضیات",
        class: "۱A",
        teacher: "مریم محمدی",
        date: "2025-01-01",
    },
    {
        id: 2,
        subject: "زبان",
        class: "۲A",
        teacher: "رضا حسینی",
        date: "2025-01-01",
    },
    {
        id: 3,
        subject: "علوم",
        class: "۳A",
        teacher: "فاطمه یوسفی",
        date: "2025-01-01",
    },
    {
        id: 4,
        subject: "مطالعات اجتماعی",
        class: "۱B",
        teacher: "احمد امینی",
        date: "2025-01-01",
    },
    {
        id: 5,
        subject: "هنر",
        class: "۴A",
        teacher: "مهدی موسوی",
        date: "2025-01-01",
    },
    {
        id: 6,
        subject: "موسیقی",
        class: "۵A",
        teacher: "آرزو نیکو",
        date: "2025-01-01",
    },
    {
        id: 7,
        subject: "تاریخ",
        class: "۶A",
        teacher: "سعید احمدی",
        date: "2025-01-01",
    },
    {
        id: 8,
        subject: "جغرافیا",
        class: "۶B",
        teacher: "احسان سلطانی",
        date: "2025-01-01",
    },
    {
        id: 9,
        subject: "فیزیک",
        class: "۷A",
        teacher: "زهرا آذر",
        date: "2025-01-01",
    },
    {
        id: 10,
        subject: "شیمی",
        class: "۸A",
        teacher: "مونا سلیمانی",
        date: "2025-01-01",
    },
];

export const assignmentsData = [
    {
        id: 1,
        subject: "ریاضیات",
        class: "۱A",
        teacher: "کامران صالحی",
        dueDate: "2025-01-01",
    },
    {
        id: 2,
        subject: "زبان",
        class: "۲A",
        teacher: "مریم رضایی",
        dueDate: "2025-01-01",
    },
    {
        id: 3,
        subject: "علوم",
        class: "۳A",
        teacher: "سینا اکبری",
        dueDate: "2025-01-01",
    },
    {
        id: 4,
        subject: "مطالعات اجتماعی",
        class: "۱B",
        teacher: "علی زارعی",
        dueDate: "2025-01-01",
    },
    {
        id: 5,
        subject: "هنر",
        class: "۴A",
        teacher: "زهرا تهرانی",
        dueDate: "2025-01-01",
    },
    {
        id: 6,
        subject: "موسیقی",
        class: "۵A",
        teacher: "ناهید محمدی",
        dueDate: "2025-01-01",
    },
    {
        id: 7,
        subject: "تاریخ",
        class: "۶A",
        teacher: "سید علی موسوی",
        dueDate: "2025-01-01",
    },
    {
        id: 8,
        subject: "جغرافیا",
        class: "۶B",
        teacher: "مهران سلیمانی",
        dueDate: "2025-01-01",
    },
    {
        id: 9,
        subject: "فیزیک",
        class: "۷A",
        teacher: "مریم جعفری",
        dueDate: "2025-01-01",
    },
    {
        id: 10,
        subject: "شیمی",
        class: "۸A",
        teacher: "حسین بهرامی",
        dueDate: "2025-01-01",
    },
];

export const resultsData = [
    {
        id: 1,
        subject: "ریاضیات",
        class: "۱A",
        teacher: "محمد حسن‌پور",
        student: "سارا حسینی",
        date: "2025-01-01",
        type: "آزمون",
        score: 90,
    },
    {
        id: 2,
        subject: "زبان",
        class: "۲A",
        teacher: "محمد حسن‌پور",
        student: "سارا حسینی",
        date: "2025-01-01",
        type: "آزمون",
        score: 90,
    },
    {
        id: 3,
        subject: "علوم",
        class: "۳A",
        teacher: "محمد حسن‌پور",
        student: "سارا حسینی",
        date: "2025-01-01",
        type: "آزمون",
        score: 90,
    },
    {
        id: 4,
        subject: "مطالعات اجتماعی",
        class: "۱B",
        teacher: "محمد حسن‌پور",
        student: "سارا حسینی",
        date: "2025-01-01",
        type: "آزمون",
        score: 90,
    },
    {
        id: 5,
        subject: "هنر",
        class: "۴A",
        teacher: "محمد حسن‌پور",
        student: "سارا حسینی",
        date: "2025-01-01",
        type: "آزمون",
        score: 90,
    },
    {
        id: 6,
        subject: "موسیقی",
        class: "۵A",
        teacher: "محمد حسن‌پور",
        student: "سارا حسینی",
        date: "2025-01-01",
        type: "آزمون",
        score: 90,
    },
    {
        id: 7,
        subject: "تاریخ",
        class: "۶A",
        teacher: "محمد حسن‌پور",
        student: "سارا حسینی",
        date: "2025-01-01",
        type: "آزمون",
        score: 90,
    },
    {
        id: 8,
        subject: "جغرافیا",
        class: "۶B",
        teacher: "محمد حسن‌پور",
        student: "سارا حسینی",
        date: "2025-01-01",
        type: "آزمون",
        score: 90,
    },
    {
        id: 9,
        subject: "فیزیک",
        class: "۷A",
        teacher: "محمد حسن‌پور",
        student: "سارا حسینی",
        date: "2025-01-01",
        type: "آزمون",
        score: 90,
    },
    {
        id: 10,
        subject: "شیمی",
        class: "۸A",
        teacher: "محمد حسن‌پور",
        student: "سارا حسینی",
        date: "2025-01-01",
        type: "آزمون",
        score: 90,
    },
];

export const eventsData = [
    {
        id: 1,
        title: "تور دریاچه",
        class: "1A",
        date: "2025-01-01",
        startTime: "10:00",
        endTime: "11:00",
    },
    {
        id: 2,
        title: "پیک نیک",
        class: "2A",
        date: "2025-01-01",
        startTime: "10:00",
        endTime: "11:00",
    },
    {
        id: 3,
        title: "تور ساحل",
        class: "3A",
        date: "2025-01-01",
        startTime: "10:00",
        endTime: "11:00",
    },
    {
        id: 4,
        title: "تور موزه",
        class: "4A",
        date: "2025-01-01",
        startTime: "10:00",
        endTime: "11:00",
    },
    {
        id: 5,
        title: "کنسرت موسیقی",
        class: "5A",
        date: "2025-01-01",
        startTime: "10:00",
        endTime: "11:00",
    },
    {
        id: 6,
        title: "نمایش شعبده‌بازی",
        class: "1B",
        date: "2025-01-01",
        startTime: "10:00",
        endTime: "11:00",
    },
    {
        id: 7,
        title: "تور دریاچه",
        class: "2B",
        date: "2025-01-01",
        startTime: "10:00",
        endTime: "11:00",
    },
    {
        id: 8,
        title: "مسابقه دوچرخه‌سواری",
        class: "3B",
        date: "2025-01-01",
        startTime: "10:00",
        endTime: "11:00",
    },
    {
        id: 9,
        title: "نمایشگاه هنر",
        class: "4B",
        date: "2025-01-01",
        startTime: "10:00",
        endTime: "11:00",
    },
    {
        id: 10,
        title: "مسابقات ورزشی",
        class: "5B",
        date: "2025-01-01",
        startTime: "10:00",
        endTime: "11:00",
    },
];

export const announcementsData = [
    {
        id: 1,
        title: "آزمون ریاضی کلاس 4A",
        class: "4A",
        date: "2025-01-01",
    },
    {
        id: 2,
        title: "آزمون ریاضی کلاس 3A",
        class: "3A",
        date: "2025-01-01",
    },
    {
        id: 3,
        title: "آزمون ریاضی کلاس 3B",
        class: "3B",
        date: "2025-01-01",
    },
    {
        id: 4,
        title: "آزمون ریاضی کلاس 6A",
        class: "6A",
        date: "2025-01-01",
    },
    {
        id: 5,
        title: "آزمون ریاضی کلاس 8C",
        class: "8C",
        date: "2025-01-01",
    },
    {
        id: 6,
        title: "آزمون ریاضی کلاس 2A",
        class: "2A",
        date: "2025-01-01",
    },
    {
        id: 7,
        title: "آزمون ریاضی کلاس 4C",
        class: "4C",
        date: "2025-01-01",
    },
    {
        id: 8,
        title: "آزمون ریاضی کلاس 4B",
        class: "4B",
        date: "2025-01-01",
    },
    {
        id: 9,
        title: "آزمون ریاضی کلاس 3C",
        class: "3C",
        date: "2025-01-01",
    },
    {
        id: 10,
        title: "آزمون ریاضی کلاس 1C",
        class: "1C",
        date: "2025-01-01",
    },
];

// YOU SHOULD CHANGE THE DATES OF THE EVENTS TO THE CURRENT DATE TO SEE THE EVENTS ON THE CALENDAR
export enum LessonsCode {
    Core = "C",
    Specialized = "S",
    General = "G",
    Physical = "P",
    Lab = "L",
}

export const LESSON_CODE_COLORS = {
    C: "#859F3D",
    S: "#9EDF9C",
    G: "#608BC1",
    P: "#D4BEE4",
    L: "#FFF100",
};

export const calendarEvents = [
    {
        title: "ریاضی",
        allDay: false,
        start: new Date(2024, 11, 8, 8, 0),
        end: new Date(2024, 11, 8, 8, 50),
        data: {
            id: 1,
            code: "C",
            title: "آزمون ریاضی کلاس 4A",
            class: "4A",
            date: "2025-01-01",
        },
    },
    {
        title: "زبان",
        allDay: false,
        start: new Date(2024, 11, 8, 9, 0),
        end: new Date(2024, 11, 8, 9, 50),
        data: {
            id: 2,
            code: "G",
            title: "آزمون زبان کلاس 3A",
            class: "3A",
            date: "2025-01-01",
        },
    },
    {
        title: "زیست‌",
        allDay: false,
        start: new Date(2024, 11, 8, 10, 0),
        end: new Date(2024, 11, 8, 10, 50),
        data: {
            id: 3,
            code: "C",
            title: "آزمون زیست‌ کلاس 3B",
            class: "3B",
            date: "2025-01-01",
        },
    },
    {
        title: "فیزیک",
        allDay: false,
        start: new Date(2024, 11, 8, 11, 0),
        end: new Date(2024, 11, 8, 11, 50),
        data: {
            id: 4,
            code: "C",
            title: "آزمون فیزیک کلاس 6A",
            class: "6A",
            date: "2025-01-01",
        },
    },
    {
        title: "شیمی",
        allDay: false,
        start: new Date(2024, 11, 8, 13, 0),
        end: new Date(2024, 11, 8, 13, 50),
        data: {
            id: 5,
            code: "C",
            title: "آزمون شیمی کلاس 8C",
            class: "8C",
            date: "2025-01-01",
        },
    },
    {
        title: "تاریخ",
        allDay: false,
        start: new Date(2024, 11, 8, 14, 0),
        end: new Date(2024, 11, 8, 14, 50),
        data: {
            id: 6,
            code: "G",
            title: "آزمون تاریخ کلاس 8B",
            class: "8B",
            date: "2025-01-01",
        },
    },
    {
        title: "زبان",
        allDay: false,
        start: new Date(2024, 11, 9, 9, 0),
        end: new Date(2024, 11, 9, 9, 50),
        data: {
            id: 7,
            code: "G",
            title: "آزمون زبان کلاس 4B",
            class: "4B",
            date: "2025-01-01",
        },
    },
    {
        title: "ورزش",
        allDay: false,
        start: new Date(2024, 11, 9, 10, 0),
        end: new Date(2024, 11, 9, 10, 50),
        data: {
            id: 8,
            code: "P",
            title: "آزمون ورزش سالن ورزشی",
            class: "S",
            date: "2025-01-01",
        },
    },
    {
        title: "فیزیک",
        allDay: false,
        start: new Date(2024, 11, 9, 11, 0),
        end: new Date(2024, 11, 9, 11, 50),
        data: {
            id: 9,
            code: "C",
            title: "آزمون فیزیک کلاس 6B",
            class: "6B",
            date: "2025-01-01",
        },
    },
    {
        title: "تاریخ",
        allDay: false,
        start: new Date(2024, 11, 9, 14, 0),
        end: new Date(2024, 11, 9, 14, 50),
        data: {
            id: 10,
            code: "G",
            title: "آزمون تاریخ کلاس 8A",
            class: "8A",
            date: "2025-01-01",
        },
    },
    {
        title: "ریاضی",
        allDay: false,
        start: new Date(2024, 11, 10, 8, 0),
        end: new Date(2024, 11, 10, 8, 50),
        data: {
            id: 11,
            code: "C",
            title: "آزمون ریاضی کلاس 4A",
            class: "4A",
            date: "2025-01-01",
        },
    },
    {
        title: "زیست‌",
        allDay: false,
        start: new Date(2024, 11, 10, 10, 0),
        end: new Date(2024, 11, 10, 10, 50),
        data: {
            id: 12,
            code: "C",
            title: "آزمون زیست‌ کلاس 5A",
            class: "5A",
            date: "2025-01-01",
        },
    },
    {
        title: "شیمی",
        allDay: false,
        start: new Date(2024, 11, 10, 13, 0),
        end: new Date(2024, 11, 10, 13, 50),
        data: {
            id: 13,
            code: "C",
            title: "آزمون شیمی کلاس 6A",
            class: "6A",
            date: "2025-01-01",
        },
    },
    {
        title: "آزفیزیک",
        allDay: false,
        start: new Date(2024, 11, 10, 14, 0),
        end: new Date(2024, 11, 10, 14, 50),
        data: {
            id: 14,
            code: "L",
            title: "آزمون آزفیزیک آزمایشگاه اصلی",
            class: "ML",
            date: "2025-01-01",
        },
    },
    {
        title: "زبان",
        allDay: false,
        start: new Date(2024, 11, 11, 9, 0),
        end: new Date(2024, 11, 11, 9, 50),
        data: {
            id: 15,
            code: "G",
            title: "آزمون زبان کلاس 3B",
            class: "3B",
            date: "2025-01-01",
        },
    },
    {
        title: "زیست‌",
        allDay: false,
        start: new Date(2024, 11, 11, 10, 0),
        end: new Date(2024, 11, 11, 10, 50),
        data: {
            id: 16,
            code: "C",
            title: "آزمون زیست‌ کلاس 4B",
            class: "4B",
            date: "2025-01-01",
        },
    },
    {
        title: "فیزیک",
        allDay: false,
        start: new Date(2024, 11, 11, 11, 0),
        end: new Date(2024, 11, 11, 11, 50),
        data: {
            id: 17,
            code: "C",
            title: "آزمون فیزیک کلاس 5B",
            class: "5B",
            date: "2025-01-01",
        },
    },
    {
        title: "تاریخ",
        allDay: false,
        start: new Date(2024, 11, 11, 14, 0),
        end: new Date(2024, 11, 11, 14, 50),
        data: {
            id: 18,
            code: "G",
            title: "آزمون تاریخ کلاس 7B",
            class: "7B",
            date: "2025-01-01",
        },
    },
    {
        title: "ریاضی",
        allDay: false,
        start: new Date(2024, 11, 12, 8, 0),
        end: new Date(2024, 11, 12, 8, 50),
        data: {
            id: 19,
            code: "C",
            title: "آزمون ریاضی کلاس 3A",
            class: "3A",
            date: "2025-01-01",
        },
    },
    {
        title: "زبان",
        allDay: false,
        start: new Date(2024, 11, 12, 9, 0),
        end: new Date(2024, 11, 12, 9, 50),
        data: {
            id: 20,
            code: "G",
            title: "آزمون زبان کلاس 4A",
            class: "4A",
            date: "2025-01-01",
        },
    },
    {
        title: "فیزیک",
        allDay: false,
        start: new Date(2024, 11, 12, 11, 0),
        end: new Date(2024, 11, 12, 11, 50),
        data: {
            id: 21,
            code: "C",
            title: "آزمون فیزیک کلاس 5A",
            class: "5A",
            date: "2025-01-01",
        },
    },
    {
        title: "شیمی",
        allDay: false,
        start: new Date(2024, 11, 12, 13, 0),
        end: new Date(2024, 11, 12, 13, 50),
        data: {
            id: 22,
            code: "C",
            title: "آزمون شیمی کلاس 6A",
            class: "6A",
            date: "2025-01-01",
        },
    },
    {
        title: "تاریخ",
        allDay: false,
        start: new Date(2024, 11, 12, 14, 0),
        end: new Date(2024, 11, 12, 14, 50),
        data: {
            id: 23,
            code: "G",
            title: "آزمون تاریخ کلاس 7A",
            class: "7A",
            date: "2025-01-01",
        },
    },
];
